x="Hallo World"
print(x)
x1=x.capitalize()
print(x1)
x2=x.casefold()
print(x2)
x3=x.title()
print(x3)
x4=x.swapcase()
print(x4)
x5=x.upper()
print(x5)
x6=x.lower()
print(x6)
print(x.center(20,"1"))
print(x.ljust(20,"2"))
print(x.rjust(20,"3"))
print(x.zfill(20))
print(x.count("o",0,8))
print(x.find("o"))
print(x.rfind("o"))
print(x.replace("World","Fellow"))
table=x.maketrans("ABCDEFG","1234567","D")
print("Attack the D point!".translate(table))
print(x.startswith("H"),x.endswith("D"))
if x.startswith(("A","B","C","D","E","F","G","H")):
    print(x[0],"true")
else:print("false")
